### PR TITLE
#52

### PR DESCRIPTION
**Pull request by ghost**
Fixing some margin problem and tidying up code

### CODE REVIEW

**Comment by FreeTrade** [comment]
Cool. In you github repository settings, could you check publish to github pages, and send me the url, this will make it easy for me to see the adjustments you've made before merging your pull request.

**Comment by FreeTrade** [comment]
Also recommend making matching changes for nightmode

**Comment by ghost** [comment]
Here you go: https://lte13.github.io/memberapp.github.io/

**Comment by ghost** [comment]
> 
> 
> Also recommend making matching changes for nightmode

Yup, I will check that too. I didn't look into it too much, but it could be that the night mode just changes color.

**Pull request merged**
