### PR TITLE
Reddit nigtht mode added

### PR DESCRIPTION
**Pull request by Telesfor1**

### CODE REVIEW

**Review by FreeTrade — COMMENTED** [review]
Thanks for this, is there somewhere I can view it?

Also I've created some contribution guidelines -
https://github.com/FreeTrade/memberdev/blob/master/CONTRIBUTING.md

**Review by FreeTrade — COMMENTED** [review]
It looks like there are a few unrelated changes here - not sure what effect changing the href will have when using as a desktop app - also some unrelated formatting changes on the footer that make it tough to read.

n.b. review https://github.com/FreeTrade/memberdev/blob/master/CONTRIBUTING.md

**Comment by FreeTrade** [comment]
Need a submission to the dev chain of 'nightmode.css' with just the changes - Would you like to do this so your name is on the commit, or I can do this with your permission? Let me know

**Comment by Telesfor1** [comment]
You can see it here https://memberdev.liiil.eu . If you like it you can take my nigtmode.css and implement it on your member. I need a articlenight.css for article night mode.

**Pull request closed without merging**
